version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 11s
      timeout: 20s
      retries: 10

    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    command: /start-web.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - "db:database"
volumes:
  mysql_data: